[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_vesting = "HWaGc49AZC3Aim9M1VBFAhgLdmw9Xp7T7QF4K9kgpuLh"

[registry]
url = "https://api.apr.dev"

[provider]
# local
cluster = "http://localhost:8899"
# dev
# cluster = "https://api.devnet.solana.com"
wallet = "/home/david/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
