[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_vesting = "DzJ68fvNC6PNfZYQzjSNiyLxgcxHD3nkRGsBAjyGTWyd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rohan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
