[toolchain]
anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_vesting = "HK2Awb6Y8baCCvgRqof4fgeK5L87XTi3K1FPFhTFjYVG"

[registry]
url = "https://api.apr.dev"

[provider]
# local
# cluster = "http://localhost:8899"
# dev
 cluster = "https://api.devnet.solana.com"
wallet = "/Users/david/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
